### ISSUE TITLE
POSIX compatibility for scripts on deploy host

### ISSUE THREAD

**Issue by bharendt** [edeliver/edeliver#143]
... and warn or abort if bash is not the default shell on the build host. See #124.

**Comment by bitwalker** [comment]
Just as an FYI, both exrm and distillery attempt to only use portable `sh` features, any bash-isms are considered a bug for this reason. I don't know that this really changes anything in edeliver, but if possible, I'd definitely encourage sticking to `sh`-only features!

**Comment by bharendt** [comment]
Downgrade to POSIX only features for the whole edeliver bash software would not make sense. But I agree, making the scripts on the deploy hosts POSIX compatible is a good idea and matches the goal of edeliver quite well, to have as few as possible dependencies on the deploy hosts. I add some information here about what can't be used then as reference for myself:

  - [bash POSIX mode](http://www.gnu.org/software/bash/manual/html_node/Bash-POSIX-Mode.html)
  - [single bracket conditions](http://mywiki.wooledge.org/BashFAQ/031)

**Comment by meatherly** [comment]
👍 Yeah this one got me today. It fails in a strange way. For instance, it just says `sh: 1: source: not found` but it still says the deploy was successful when it wasn't. The tar wasn't even extracted for some reason. I was able to fix it by looking at this SO post: https://stackoverflow.com/questions/13702425/source-command-not-found-in-sh-shell

Maybe we can add a Caveats section?
