### ISSUE TITLE
How to post task

### ISSUE THREAD

**Issue by blisscs** [edeliver/edeliver#152]
Similar to pre_erlang_get_and_update_deps showed on the README
Hello,
I have one question to ask here. 
I would like to do a post deployment task. I would like to create a symlink from latest releases to the share upload directory.
For examples:
After deploy app with 1.0.0 the 'lib' directory structure will have folder app-1.0.0
Then I upgrade to 1.1.0 the 'lib' directory structure will have another folder app-1.1.0
If I have another 'uploads' directory just outside the 'lib' directory here, I would like to create a symlink from 'app-x.x.x/uploads' to the 'uploads' directory outside the 'lib'. 

I wonder if there is any correct way to do this.
By doing this I could manage to share uploads files among each deploy of phoenix app through edeliver

Thank you
Dev.

**Comment by blisscs** [comment]
After further research I see can do something like this -

post_upgrade_release(){
  status "Link Share upload folder"
  __sync_remote "
    # runs the commands on the build host
    [ -f ~/.bashrc ] && source ~/.bashrc # load profile (optional)

    # fail if any command fails (recommended)
    set -e

    cd '$DELIVER_TO/$APP'
    ln -s uploads 'lib/$APP-XXX/uploads'
  "
}

One more thing that I missing is how to get the current release version. so that I can use it instead of XXX here.

**Comment by DavidOliver** [comment]
I think [this](https://github.com/boldpoker/edeliver/wiki/Symlink-static-for-nginx-or-apache) might help. :)

**Comment by lessless** [comment]
Thanks folks! Clothing this now.
