### ISSUE TITLE
DELIVER_TO QUESTION

### ISSUE THREAD

**Issue by blisscs** [edeliver/edeliver#155]
Hello,

I see in the readme that there is only one DELIVER_TO option.
How to specify DELIVER_TO for staging and another for production?

Thank you very much
Dev.

**Comment by bharendt** [comment]
Hello, 

For staging environment the deploy path can be set by the `TEST_AT` variable in the config.

**Comment by blisscs** [comment]
Thank you @bharendt.
I try TEST_AT it is deploying the staging to the right directory now.
Now I am getting issues with   LINK_SYS_CONFIG, LINK_VM_ARGS. What's names shall use to configure these two for staging environment

**Comment by bharendt** [comment]
`LINK_SYS_CONFIG` and `LINK_VM_ARGS` are used for the build process only. They point to the same destination on each deploy host. E.g. if you set `LINK_SYS_CONFIG` to `/etc/my-server.config` you should create that file (the link destination) also on your staging host(s) containing your staging configuration.

**Comment by blisscs** [comment]
In the case that staging and the production are on the same server. This wouldn't work. Are there ways to write task that after deploy delete both files and then do ln -s to the files to make it works.

Dev

**Comment by bharendt** [comment]
I would recommend to use a different `STAGING_USER` and `PRODUCTION_USER ` then, if staging and production environment runs on the same host. You could link the config then to the different home directories, e.g. to `~/my-server.config`.

**Comment by blisscs** [comment]
Thank you @bharendt that would one of the way to make it works.
But I really think that correct way solve to this problem  would to have a prefix in front of these variables like -
STAGING_DEPLOY_TO, STAGING_LINK_SYS_CONFIG, STAGING_LINK_VM_ARGS

In this way it would be possible to have more kind of hosts for example BETA_HOSTS, FEATURE_A_HOSTS, FEATURE_B_HOSTS in the future. And we can use similar logic here.

What do you think?

**Comment by lessless** [comment]
I suspect that staging and production should not share the same machine. In case there is no other option release can be packed in the docker images.
