### ISSUE TITLE
Failed to detect exrm version.

### ISSUE THREAD

**Issue by GildedHonour** [edeliver/edeliver#159]
For my previous project it worked fine more or less, I had to spend some time to get it to work. For the current one not 

```
Generated my_app app
-----> Detecting exrm version
cat: deps/exrm/mix.exs: No such file or directory

Failed to detect exrm version.

Please set EXRM_VERSION_MAJOR, EXRM_VERSION_MINOR and EXRM_VERSION_PATCH
in the console or the config file.

Detected '' as major,
         '' as minor
     and '' as patch version.

```

What in my mix.exs is what is written in your readme:

```
     {:edeliver, "~> 1.4.0"},
     {:distillery, ">= 0.8.0", warn_missing: false},
#     {:distillery, "~> 0.9.9", warn_missing: false},

```

I won't be surprised if you fix this bug but that'll bring another one.

**Comment by bharendt** [comment]
You can try to set `USING_DISTILLERY` to `true` in your config to force edeliver to consider your project using distillery as release tool. If the auto detection failed, the main question is whether your project is an umbrella project and if yes, in which `mix.exs` file the distillery was added as dependency (the main one or from an umbrella project).

**Comment by GildedHonour** [comment]
```
using mix to generate release
==> Loading configuration..
==> You are missing a release config file. Run the release.init task first
```

**Comment by GildedHonour** [comment]
why is it missing? it's not in .gitignore.

**Comment by anildigital** [comment]
:+1:

**Comment by lessless** [comment]
Hi folks,

are your configs commited to the repo?

**Comment by lessless** [comment]
Exrm is not support anymore as of 1.4.6
