### ISSUE TITLE
mix edeliver check release displays: Unknown command check.

### ISSUE THREAD

**Issue by hut8** [edeliver/edeliver#166]
### Environment

* Edeliver version (`mix edeliver --version`): `edeliver v1.4.0`
* Elixir version (`elixir -v`): 
```
Erlang/OTP 19 [erts-8.1] [source-4cc2ce3] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.3.3
```
* Build tool and version (distillery|exrm): distillery
* Operating system (on build / deploy hosts): Ubuntu Xenial
* Are you using an umbrella project (yes|no): no

### Current behavior

When I run `mix help edeliver`, I am shown (inter alia):

```
Local Commands:

  • mix edeliver check release|config [--version=<release-version>]
```

When I run `mix edeliver check release`, I get the help text and `Unknown command check.`

### Expected behavior

`mix edeliver check release` should run that particular task implementation

**Comment by johannesE** [comment]
I can confirm the same behavior with v1.4.2

**Comment by lessless** [comment]
It seems that check command is not implement and I don't know what was the original idea. If somebody from the @edeliver/owners can outline the strategy we can try to forge it somewhere later.
