### ISSUE TITLE
Update configuration for running app

### ISSUE THREAD

**Issue by lucasm-iRonin** [edeliver/edeliver#173]
Hi,
I have a question. How can I rebuild the app and deploy (with hot module upgrade) if I just updated the config file on the server (the one that gets symlinked to tmp dir).

**Comment by lessless** [comment]
Hi @lucasm-iRonin , 

What config are you exactly talking about? I don't see any symlinks in my project

**Comment by lucasm-iRonin** [comment]
@lessless I'm sorry but it was so long ago that I don't even remember.

**Comment by lessless** [comment]
No problems! I'll close the issue then.

Thanks!
