### ISSUE TITLE
** (MatchError) no match of right hand side value: {:error, :enoent}

### ISSUE THREAD

**Issue by GildedHonour** [edeliver/edeliver#181]
I have an error while generating a release for my Phoenix/Elixir web application, here's a command which causes it:
    

    $ MIX_ENV="prod" LINK_SYS_CONFIG="" LINK_VM_ARGS="" APP="my_web_app123" AUTO_VERSION="" \
      BRANCH="master" SKIP_RELUP_MODIFICATIONS="" RELUP_MODIFICATION_MODULE="" mix  release \
      --no-confirm-missing --verbosity=normal
    Building release with MIX_ENV=prod.

    ** (MatchError) no match of right hand side value: {:error, :enoent}
      /home/my_web_user123/my_web_app123/builds/deps/relx/src/rlx_prv_assembler.erl:510: :rlx_prv_assembler.include_erts/4
      /home/my_web_user123/my_web_app123/builds/deps/relx/src/rlx_prv_assembler.erl:59: :rlx_prv_assembler.do/1
      /home/my_web_user123/my_web_app123/builds/deps/relx/src/relx.erl:308: :relx.run_provider/2
      (stdlib) lists.erl:1263: :lists.foldl/3
      /home/my_web_user123/my_web_app123/builds/deps/relx/src/relx.erl:291: :relx.run_providers_for_actions/2
      lib/exrm/utils/utils.ex:105: ReleaseManager.Utils.relx/5
      lib/mix/tasks/release.ex:339: anonymous fn/4 in Mix.Tasks.Release.do_release/1
      lib/ex_unit/capture_io.ex:146: ExUnit.CaptureIO.do_capture_io/2

Any ideas how to fix it?

**Comment by hut8** [comment]
Seems like this would be more of a bug in relx, no? `edeliver` doesn't provide `mix release`.

**Comment by syamilmj** [comment]
I found the list here to be quite helpful when debugging these kinds of error: http://erlang.org/doc/man/file.html

`:enoent A component of Dir does not exist.`

**Comment by hopewise** [comment]
I am stuck at this issue and can't deploy a new release, any idea?

**Comment by lessless** [comment]
Closing this issue as it not related to edeliver
