### ISSUE TITLE
hexdocs "Usage" section is broken

### ISSUE THREAD

**Issue by vizvamitra** [edeliver/edeliver#190]
### Environment

docs at hexdocs.pm for edeliver [1.3.0](https://hexdocs.pm/edeliver/1.3.0/readme.html) and [1.4.0](https://hexdocs.pm/edeliver/1.4.0/readme.html)

### Current behavior

"Usage" section contains raw markdown

### Expected behavior

"Usage" section contains nice-looking html

**Comment by shisongsong** [comment]
Yes, I found it too, it's funny.

**Comment by lessless** [comment]
Hi @vizvamitra,

Sounds like a good issue for submitting a PR ;)
