### ISSUE TITLE
error "Please rerun with RELEASE_VERSION ...". but all has been setup already

### ISSUE THREAD

**Issue by GildedHonour** [edeliver/edeliver#191]
So far, for a few months, it's worked well, but not anymore:

    $ mix edeliver build release --verbose

		[..............]
		==> Release successfully built!
		    You can run it in one of the following ways:
		      Interactive: _build/prod/rel/my_website/bin/my_website console
		      Foreground: _build/prod/rel/my_website/bin/my_website foreground
		      Daemon: _build/prod/rel/my_website/bin/my_website start
		ls: cannot access '/home/my_user/my_website/builds/rel/my_website/releases/*/': No such file or directory
		Failed to detect generated release version at:
		my_user@11.22.33.44:/home/my_user/my_website/builds/rel/my_website/releases/

		Detected several releases:
		 A
		 remote
		 command
		 failed
		 on:
		 my_user@11.22.33.44
		 Output
		 of
		 the
		 command
		 is
		 shown
		 above
		 if
		 the
		basename: unrecognized option '--verbose'
		Try 'basename --help' for more information.
		 
		 option
		 was
		 used
		 and
		 the
		 commands
		 executed
		 on
		 that
		 remote
		 host
		 are
		 printed
		 below
		 for
		 debugging
		 purposes:
		 FAILED
		 with
		 exit
		 status
		 2:
		 ssh
		basename: invalid option -- 'o'
		Try 'basename --help' for more information.
		 
		 ConnectTimeout=3
		 my_user@11.22.33.44
		 ls
		basename: invalid option -- 'A'
		Try 'basename --help' for more information.
		 
		 *
		Please rerun with RELEASE_VERSION=x environment variable set.

My .deliver/config doesn't contain RELEASE_VERSION but it does contain:

    GIT_CLEAN_PATHS=${GIT_CLEAN_PATHS:="rel"}

I've also set RELEASE_VERSION=0.1.2 on my server but it didn't help. 

Elixir 1.4.0

**Comment by GildedHonour** [comment]
up

**Comment by mikelat** [comment]
I too am having the same error after upgrading to 1.4, and edeliever worked before that.

**Comment by pikender** [comment]
I am facing same error too :disappointed:

**Comment by pikender** [comment]
@GildedHonour @mikelat `adding output_dir under environment in rel/config.exs` fixes the problem as mentioned here https://github.com/boldpoker/edeliver/issues/182#issuecomment-269670951

**Comment by lessless** [comment]
thanks @pikender,
Closing this issue in favor of #182, which I hope we will have more time to look on.
