### ISSUE TITLE
AUTO_VERSION doesn't use branch when set new version

### ISSUE THREAD

**Issue by gpad** [edeliver/edeliver#208]
If you try tu use `AUTO_VERSION=commit-count+git-revision+branch` with distillery the release is always marked as master also if you are on different branch.

The bug probably is located in this [here](https://github.com/boldpoker/edeliver/blob/2f2abd952fb960f1250cb1a277eac709dec28b8b/libexec/erlang#L176) where it's not pass the `BRANCH` variable. Instead in this [line](https://github.com/boldpoker/edeliver/blob/2f2abd952fb960f1250cb1a277eac709dec28b8b/libexec/erlang#L186) it's passed.

I created a [pull request](https://github.com/boldpoker/edeliver/pull/207)  and I test in my environment where the test is present and now it's corrected.

### Environment

* Edeliver version (`mix edeliver --version`): edeliver v1.4.2
* Elixir version (`elixir -v`): Elixir 1.4.1
* Build tool and version (distillery|exrm): distillery
* Operating system (on build / deploy hosts): linux (ubuntu 16.04/14.04)
* Are you using an umbrella project (yes|no): no

### Verbose output

* Are there more information when running with `--verbose`?
* Can you narrow down the code line causing the issue when running with `--debug`?
* Please remove any private data from the output before pasting it here (login credentials, ip addresses user names etc.)

### Current behavior

mix edeliver build release --branch=staging --mix-env=staging

generate 0.0.1+174-18ca1a0-master

### Expected behavior

should generate 0.0.1+174-18ca1a0-staging

**Comment by ryanswapp** [comment]
I believe I've encountered the same issue. When running:
```
mix edeliver upgrade production —auto-version=git-revision 
```
The FROM option is set to "Node" instead of the last revision hash. 

This command has worked for me a number of times and started failing today. The only thing different is that my local machine is running Elixir 1.4.2 instead of 1.3.2. The remote machine still has the same elixir version. I am on edeliver 1.4.0.

**Comment by gpad** [comment]
@ryanswapp If you want a quick solution you can check it out my [pull request ](https://github.com/boldpoker/edeliver/pull/207).

**Comment by ryanswapp** [comment]
@gpad thanks! Interestingly, I nuked the app on the remote server and then did a fresh build and deploy and all seems to be working. I've done a couple upgrades since then and it's all working fine. I suspect my issue had to do with upgrading to Elixir 1.4.

**Comment by lessless** [comment]
Closing, since PR was merged.
