### ISSUE TITLE
How to replace OS env vars

### ISSUE THREAD

**Issue by jamiesunderland** [edeliver/edeliver#213]
I have very little idea how to use env vars as run time variables with edeliver + distillery. I get how to do it locally with distillery when building a release on my local machine but I cannot figure out how to use REPLACE_OS_VARS=true on a deployed node. 

Currently on one of my example runtime instances I have 
``` 
# /home/runtime_instance/.profile
export DB_USER="xxx";
export DB_PASSWORD="xxx";
```
and in my build instance I have
```
# /home/build_instance/.profile
REPLACE_OS_VARS=true
```

In my prod.exs I have
```
config :my_app, MyApp.Repo,
  adapter: Ecto.Adapters.Postgres,
  database: System.get_env("${DB_NAME}"),
  username: System.get_env("${DB_USER}"),
  password: System.get_env("${DB_PASSWORD}"),
  hostname: System.get_env("${DB_HOST}"),
  pool_size: System.get_env("${DB_POOL}"
```

my staging servers and prod servers should point to different db instances. How can I interpolate the env vars with edeliver and distillery?

**Comment by DavidOliver** [comment]
I'm using env vars at production via systemd. [Phoenix in Production with systemd](http://mfeckie.github.io/Phoenix-In-Production-With-Systemd/) and [Elixir apps as systemd Services](https://elixirforum.com/t/elixir-apps-as-systemd-services/2400) helped me a great deal.

Example config notes follow.

### prod.exs

My reverse proxy webserver ([Hiawatha](https://www.hiawatha-webserver.org/)) is set to enforce use of https (thus hardcoded `443` for URLs here), and forwards to the app at a custom port (thus `MYAPP_PORT` here).

To use env vars from the production environment, we don't use `System.get_env/1` as that gets an environment variable [at build time](https://elixirforum.com/t/what-is-the-difference-between-using-system-port-and-system-get-env-port-in-deployment/1975), not run time.

```elixir
use Mix.Config

## General
config :MyApp, MyApp.Endpoint,
  http: [port: "${MYAPP_PORT}"],
  url: [host: "${MYAPP_HOSTNAME}", port: 443],
  cache_static_manifest: "priv/static/manifest.json",
  secret_key_base: "${MYAPP_SECRET_KEY_BASE}",
  server: true,
  root: ".",
  version: Mix.Project.config[:version]

config :logger, level: :info

## OTP releases
# Instruct Phoenix to start the server for all endpoints:
config :phoenix, :serve_endpoints, true
# Alternatively, configure which server to start per endpoint:
#config :MyApp, MyApp.Endpoint, server: true

## Repos
config :MyApp, MyApp.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "${MYAPP_DB_USERNAME}",
  password: "${MYAPP_DB_PASSWORD}",
  database: "${MYAPP_DB_DATABASE}",
  hostname: "${MYAPP_DB_HOSTNAME}",
  pool_size: "${MYAPP_DB_POOLSIZE}"
```

### /etc/systemd/system/myapp.service

```
[Unit]
Description=My App
After=network.target
Requires=network.target

[Service]
Type=simple
WorkingDirectory=/var/www/myapp/app/myapp
User=myunixuser
Group=myunixgroup
RemainAfterExit=yes
Restart=on-failure
RestartSec=2
EnvironmentFile=/var/www/myapp/env_vars
ExecStart=/var/www/myapp/app/myapp/bin/myapp start
ExecStop=/var/www/myapp/app/myapp/bin/myapp stop
#PIDFile=

[Install]
WantedBy=multi-user.target
```

### /var/www/myapp/env_vars

```
REPLACE_OS_VARS=true
HOME=/var/www/myapp/app/myapp/
MIX_ENV=prod
LANG=en_GB.UTF-8
MYAPP_PORT=4023
MYAPP_HOSTNAME=myapp.com
MYAPP_SECRET_KEY_BASE=DH3d38d...
MYAPP_DB_USERNAME=dbrole
MYAPP_DB_PASSWORD=dbpassword
MYAPP_DB_DATABASE=dbname
MYAPP_DB_HOSTNAME=localhost
MYAPP_DB_POOLSIZE=20
```

### Server app service commands

SSH'ed into production server, once the app has been built and deployed, including migrations:

Start app:

    # systemctl start myapp.service

Check app status:

    # systemctl status myapp.service

Set app to start on boot:

    # systemctl enable myapp.service

**Comment by DavidOliver** [comment]
I should add that I found that, as I'm using an environment variable for the app port and systemd-set unit environment variables, `mix edeliver restart production` fails to successfully restart the app. (I think this is because the port number is required to be written to an Erlang config file; confirmation/clarification appreciated!)

So I use this command to restart the app from my workstation instead:

    ssh -t user@host 'sudo systemctl restart myapp.service'

**Comment by sohjiro** [comment]
Hi @jamiesunderland I don't know if you still have the same problem but here it's my setup:

In my prod.secret.exs I have the following:
```elixir
config :my_app, MyApp.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: System.get_env("POSTGRESQL_USER"),
  password: System.get_env("POSTGRESQL_PASS"),
  database: System.get_env("POSTGRESQL_DB"),
  hostname: System.get_env("PORT_5432_TCP_ADDR"),
  port:     System.get_env("PORT_5432_TCP_PORT"),
```

And in my build environment have the following in a `profile` file:
``` shell
export POSTGRESQL_USER=myapp_db_user
export POSTGRESQL_PASS=myapp_db_pass
export POSTGRESQL_DB=myapp_db_name
export AWS_PORT_5432_TCP_ADDR=myapp_db_host
export PORT_5432_TCP_PORT=myapp_db_port

export REPLACE_OS_VARS=true
```

I hope this can help you.
