### ISSUE TITLE
question:  how do I set stacktrace_depth ?

### ISSUE THREAD

**Issue by mikeni** [edeliver/edeliver#225]
I am using phoenix with cowboy.

in the config of dev, prod, and test, I am setting

config :phoenix, :stacktrace_depth, 20

however in the log files of my server, the stack is always 8 depth,

in my local development computer, mix phoenix.server produces depth of 20

it seems the stacktrace config is not applied with edeliver

**Comment by bharendt** [comment]
Did you set the `: stacktrace_depth ` option correctly for the `:phoenix` [app](https://github.com/phoenixframework/phoenix/blob/438b74255e7a4d68b4eaf1a295d0fcd201c71421/lib/phoenix.ex#L42) and is it included in the `rel/your_app/releases/version/sys.config`? You can also set it directly in the `start` function of your application. The value could also been overwritten accidentally by another application.

**Comment by mikeni** [comment]
in my "web/myapp/var/sys.config", I do see

 {phoenix,
     [{stacktrace_depth,20},{format_encoders,[{'json-api','Elixir.Poison'}]}]},

I'm checking to see if got overwritten
