### ISSUE TITLE
mix edeliver deploy upgrade command fails saying: vm.args: No such file or directory

### ISSUE THREAD

**Issue by nelsonic** [edeliver/edeliver#234]
### Precheck

+ [x] We have _successfully_ used Edeliver to "hot upgrade" a "***Hello World***" app using Travis-CI:
https://travis-ci.org/nelsonic/hello_world_edeliver/builds/259965752#L1752 so we know it's _possible_! (_but we haven't been able to do the "edeliver upgrade" for a "real" app ..._)
+ [x] Have read as much of the docs/examples & spent a chunk of time googling. 
+ [x] Opening issue as last resort _after_ asking for help on StackOverflow:
https://stackoverflow.com/questions/45478961/how-to-avoid-edeliver-deployment-error-vm-args-no-such-file-or-directory

### Current behavior

The _build_ step succeeds using the following command (_to build the upgrade_):

```
mix edeliver build upgrade --auto-version=git-revision --from=$(git rev-parse HEAD~) --to=$(git rev-parse HEAD) --verbose
```

i.e. "build the upgrade from the previous git revision to the current one"

So far, so good. "_Release successfully built!_"

![edeliver-upgrade-build-successful](https://user-images.githubusercontent.com/194400/28910525-257bae48-7825-11e7-9c1d-c2666618a00a.png)

#### `mix edeliver deploy upgrade` command fails saying: `vm.args: No such file or directory`

Sadly, when we attempt to run the "deploy upgrade" command:

```
mix edeliver deploy upgrade to production --version=1.0.3+86d55eb --verbose
```

we see the following error during deployment:

![vm.args-no-such-file-or-directory](https://user-images.githubusercontent.com/194400/28912294-98945e10-782b-11e7-8dde-638b09d3f87c.png)

```
cat: /home/hladmin/healthlocker/releases/1.0.3+86d55eb/vm.args: No such file or directory
```

### Question:

Is there a way to _not_ fail if the `vm.args` file is not present? (_i.e. ignore it's absence_)

### Environment

+ Localhost: Mac running Elixir 1.4.2
+ Build Host: **Ubuntu 16.04.2 LTS** running Elixir 1.4.5
+ `mix.exs` file: https://github.com/healthlocker/healthlocker/blob/continuous-delivery/mix.exs
+ `edeliver` version: `1.4.4`
+ Build tool: `distillery` version: `1.4.0`
+ Umbrella project: yes. 

* Edeliver version (`mix edeliver --version`):
* Elixir version (`elixir -v`):
* Build tool and version (distillery|exrm):
* Operating system (on build / deploy hosts):
* Are you using an umbrella project (yes|no):

### Verbose output

We run all our commands with `--verbose` (_see output screenshot above_)

### Expected behavior

Expect the deployment to deploy the upgrade to the VM. 

Any help much appreciated! Thanks!

**Comment by daya** [comment]
@nelsonic any new findings on this issue?

**Comment by nelsonic** [comment]
@daya, sadly not yet. I would _love_ to make some progress on _automating_ the process. 
right now we are doing the deployment _manually_ and it _sucks_! 😞

**Comment by lessless** [comment]
Hi @nelsonic,

From looking at https://github.com/bitwalker/distillery/issues/169 I guess that issue is resolved?

**Comment by nelsonic** [comment]
@lessless good question. will need to check ... (_thanks_!)
