### ISSUE TITLE
Release failed, Duplicated modules

### ISSUE THREAD

**Issue by RalphMarks** [edeliver/edeliver#236]
Hi, I'm deploying an phoenix app and when edeliver is creating the release the next message appears:

![captura de pantalla 2017-08-10 a la s 13 31 38](https://user-images.githubusercontent.com/9852856/29186553-7bf35232-7dd2-11e7-9c38-5b34716a28b9.png)

### Environment

Edeliver 1.4.4

Elixir 1.5.0

Distillery

Ubuntu:16.04

### Verbose output

![captura de pantalla 2017-08-10 a la s 13 34 35](https://user-images.githubusercontent.com/9852856/29186607-9e04426e-7dd2-11e7-8388-3866fadf0d21.png)

### Current behavior

mix edeliver build release --debug

**Comment by onelesd** [comment]
You'll need the poison and/or eiya maintainers to fix this in their module.

**Comment by lessless** [comment]
Thanks @onelesd
