### ISSUE TITLE
start command does not start the app

### ISSUE THREAD

**Issue by hopewise** [edeliver/edeliver#242]
**Environment**

Edeliver version (mix edeliver --version): 1.4.4
Elixir version (elixir -v): 1.4.1
Build tool and version (distillery|exrm): distillery 1.4.0
Operating system (on build / deploy hosts): Debian 
Are you using an umbrella project (yes|no): no

**Current behavior**

The app will not start when I do this command:
    mix edeliver start staging --verbose

What I get is:

```
EDELIVER MYAPP WITH START COMMAND

-----> starting staging servers

staging node:

  user    : admin
  host    : xx.xx.xx.xx
  path    : /home/admin
  response: 

START DONE!
```

So, the response is blank as above, and even if I am using --verbose, I don't get any detail.
If I do ssh into the server, I can start it by using `/home/admin/trackware/bin/myapp start `

in the config of edeliver: 

```
pre_erlang_get_and_update_deps() {
  local _prod_secret_path="/home/$USER/prod.secret.exs"
  if [ "$TARGET_MIX_ENV" = "prod" ]; then
    __sync_remote "
      ln -sfn '$_prod_secret_path' '$BUILD_AT/config/prod.secret.exs'

      cd '$BUILD_AT'

      mkdir -p priv/static

      mix deps.get

      APP='$APP' MIX_ENV='$TARGET_MIX_ENV' $MIX_CMD phoenix.digest $SILENCE
    "
  fi
}
```

How can I debug why app will not start using `mix edeliver start staging` ?

**Comment by bigardone** [comment]
I'm having the same issue, and what I do is to ssh into the server and run manually the build to check if there are any errors while starting it.

**Comment by hopewise** [comment]
It would be more than great to get a solution for this issue..

**Comment by mxgrn** [comment]
I can add to this that manually starting the deployed release, e.g.:

    PORT=8080 ./foo_app/bin/foo_app start

... does *not* result in a running app:

```
➡ curl localhost:8080
curl: (7) Failed to connect to localhost port 8080: Connection refused

```

While starting from the code dir...

    PORT=8080 MIX_ENV=prod mix phx.server

... does:

```
➡ curl localhost:8080
<!DOCTYPE html>
<html lang="en">
  <head>
   ...
```

**Comment by mxgrn** [comment]
Ok, managed to get quite a bit further, and it seems to be related to distillery, not edeliver. After following https://hexdocs.pm/distillery/use-with-phoenix.html#configuring-your-release I was able to build a working release, which can be started manually by `PORT=8080 ./production/foo_app/bin/foo_app start`. This issue helped: https://github.com/bitwalker/distillery/issues/276

However, using edeliver to start the app remotely still doesn't work. I suppose it's related to the PORT not being set. Not sure where and when edeliver is setting the PORT. Ideas?

**Comment by Hinsei** [comment]
I was facing the same issue where running mix edeliver start production did not actually start the app remotely. 

Running PORT=8080 ./app/bin/app start worked on the remote host seemed to work.   

I managed to fix it by adding `export PORT=4000` into the remote's .profile file

**Comment by lessless** [comment]
Thanks @Hinsei,

closing the issue. Please, feel free to comment if it persists
