### ISSUE TITLE
ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory

### ISSUE THREAD

**Issue by hopewise** [edeliver/edeliver#243]
### Environment

* Edeliver version (`mix edeliver --version`):
    edeliver v1.4.4 | https://github.com/boldpoker/edeliver
* Elixir version (`elixir -v`):
    Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
    Elixir 1.4.1
* Build tool and version (distillery|exrm): distillery
* Operating system (on build / deploy hosts): macOS
* Are you using an umbrella project (yes|no): no

### Verbose output

```
➜  elixir git:(master) ✗ sudo mix edeliver deploy release to production --verbose
warning: variable "aliases" does not exist and is being expanded to "aliases()", please use parentheses to remove the ambiguity or change the variable name
  mix.exs:12

warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  mix.exs:13


DEPLOYING RELEASE OF MYAPP APP TO PRODUCTION HOSTS

-----> Authorizing hosts
Authorizing 54.93.118.4 on localhost:
54.93.118.4 ssh-rsa xxxxxx
54.93.118.4 ecdsa-sha2-nistp256 xxxxxxx
-----> Selecting release
Found 80 different versions to deploy.
Type the version you want to deploy
or set --version=X in the command line.
Versions:

 0.0.3
 0.0.4
 0.0.5
Enter Version:
0.0.5
-----> Uploading archive of release 0.0.5 from local release store
ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory
Host key verification failed.

A remote command failed on:

  54.93.118.4

Output of the command is shown above if the --verbose option
was used and the commands executed on that remote host are
printed below for debugging purposes:

FAILED with exit status 255:

ssh -o ConnectTimeout=3 54.93.118.4 
      [ -f ~/.profile ] && source ~/.profile
      set -e
      mkdir -p /home/admin/myapp  

```

### Current behavior

I can't deploy the app to production servers, as I got error:

    ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory
    Host key verification failed.

although I can ssh successfully into the production servers.

### Expected behavior

deploying the app to production servers

**Comment by shisongsong** [comment]
Did you add your `id_rsa.pub` to the server's `~/.ssh/authorized_keys`?

**Comment by hopewise** [comment]
Yes, I did, I do ssh admin@x.x.x.x to the server normally

**Comment by shisongsong** [comment]
@hopewise I had already given up, cause I got the same error, 😂

**Comment by hopewise** [comment]
@shisongsong that's sad, I am currently using ubuntu to deploy my app, which works without any issue..

**Comment by shisongsong** [comment]
@hopewise Good for you, I would try again.

**Comment by lessless** [comment]
@hopewise I'm closing this issue since it works for you now. @shisongsong feel free to let us know if you didn't figure it out.

Thanks
