### ISSUE TITLE
How can I add an arbitrary called server and deploy to it?

### ISSUE THREAD

**Issue by GildedHonour** [edeliver/edeliver#247]
I want to add a few new servers in my config such "MY_SERVER1", "MY_LOVELY_SERVER", "SERVER_I_DONT_LIKE". In the readme it describes only the standard servers titled "production", "build" and "staging":

```
STAGING_HOSTS="stage.myapp.com"
STAGING_USER="web"

DELIVER_TO="/home/web"
```
 
And

```
mix edeliver version staging
mix edeliver build staging

```

How can I add "MY_LOVELY_SERVER" for instance? How will I then deploy to it?

Moreover, I'm using this command:

> mix edeliver build release

for deploying to production which doesn't contain the name of a server at all.

**Comment by lessless** [comment]
I suspect `STAGING_HOSTS="stage.myapp.com  MY_LOVELY_SERVER"

Please use Stackoverflow, Elixirforum with `edeliver` tag or deployment channel in Slack for support questions.
