### ISSUE TITLE
umbrella app

### ISSUE THREAD

**Issue by MeterSoft** [edeliver/edeliver#250]
i have umbrella app
javascript:void(0)apps folder contain 3 application
app A
app B
app c is umbrella
A includes c
B includes c
How i can deploy A and B as different apps used deliver?.
My config

`
APP="app"

BUILD_HOST="host"
BUILD_USER="user"
BUILD_AT="/home/user/$APP/builds"

RELEASE_DIR="/home/user/$APP/builds/_build/prod/rel/$APP"

PRODUCTION_HOSTS="host"
PRODUCTION_USER="user"
DELIVER_TO="/home/user"
`
But it builds one app...

**Comment by lessless** [comment]
Please use Stackoverflow or `deployment` channel in Slack for support questions
