### ISSUE TITLE
Build upgrade fails with S3 release

### ISSUE THREAD

**Issue by dlameri** [edeliver/edeliver#255]
### Environment

* Edeliver version (`mix edeliver --version`): edeliver v1.4.4
* Elixir version (`elixir -v`): Elixir 1.5.2
* Build tool and version (distillery|exrm): distillery
* Operating system (on build / deploy hosts): Ubuntu
* Are you using an umbrella project (yes|no): no

### Current behavior

mix edeliver build upgrade --with=0.1.1+214f24c

BUILDING UPGRADE OF MERCURIO APP ON BUILD HOST

-----> Authorizing hosts
-----> Validating * version 0.1.1+214f24c is in s3 release store
-----> Ensuring hosts are ready to accept git pushes
-----> Pushing new commits with git to: *build_user*@*build_host*
-----> Resetting remote hosts to 2b8042abcfe8a2a485fab05afdc6a8b5d6347659
-----> Cleaning generated files from last build
-----> Checking out 2b8042abcfe8a2a485fab05afdc6a8b5d6347659
-----> Fetching / Updating dependencies
-----> Compiling sources
-----> Checking version of new release
-----> Uploading archive of release 0.1.1+214f24c from s3 release store
bash: line 3498: warning: here-document at line 5 delimited by end-of-file (wanted `EOF#!/usr/bin/perl')
-----> Extracting archive mercurio_0.1.1+214f24c.tar.gz
-----> Generating release
using mix to generate release
==> Loading configuration..
==> Assembling release..
==> Building release mercurio:0.1.1+2b8042a using environment prod
==> One or more direct or transitive dependencies are missing from
    :applications or :included_applications, they will not be included
    in the release:

    :fs

    This can cause your application to fail at runtime. If you are sure
    that this is not an issue, you may ignore this warning.

==> Discovered applications:

*Many apps discovered*

==> Upgrading mercurio from 0.1.1+214f24c to 0.1.1+2b8042a
==> Upgrade failed, version 0.1.1+214f24c does not exist:
    expected at: _build/prod/rel/mercurio/releases/0.1.1+214f24c

A remote command failed on:

  *build_user*@*build_host*

Output of the command is shown above and the command executed
on that host is printed below for debugging purposes:

FAILED with exit status 1:

    [ -f ~/.profile ] && source ~/.profile
    set -e
    cd /home/ubuntu/apps/mercurio
    if [ "mix" = "rebar" ]; then
      echo "using rebar to generate release"
      ./rebar   -f generate
    elif [ "mix" = "relx" ]; then
      echo "using relx to generate release"
      ./relx release
    elif [ "mix" = "mix" ]; then
      echo "using mix to generate release"
      MIX_ENV="prod" LINK_SYS_CONFIG="" LINK_VM_ARGS="" APP="mercurio" AUTO_VERSION="revision" BRANCH="master" SKIP_RELUP_MODIFICATIONS="" RELUP_MODIFICATION_MODULE="" USING_DISTILLERY="true" mix do release.version ,  release --verbose --env="prod" --name="mercurio" --upgrade --upfrom="0.1.1+214f24c"
    fi

### Expected behavior

It seems that edeliver is copying and extracting the "upfrom" version on folder "rel/mercurio/releases/0.1.1+214f24c" but distillery is searching for it on "_build/prod/rel/mercurio/releases/0.1.1+214f24c"

Am i doing something wrong or is it really a wrong behaviour of edeliver?

P.S: Mercurio is the name of my app

**Comment by lessless** [comment]
Hi @dlameri ,

Can you please try `bugs/update-default-distillery-release-folder"` branch?
Here is the dependency spec for the `mix.exs`
```
{:edeliver, github: "edeliver/edeliver", branch: "bugs/update-default-distillery-release-folder"}
```

**Comment by lessless** [comment]
Closing this issue as duplication of #182, let's continue discussion there.
