### ISSUE TITLE
pathspec 'RPC' did not match any file(s) known to git

### ISSUE THREAD

**Issue by veverkap** [edeliver/edeliver#259]
### Environment

* Edeliver version (`mix edeliver --version`):
edeliver v1.4.5
* Elixir version (`elixir -v`):
Elixir 1.6.0
* Build tool and version (distillery):
distillery 1.5.2
* Operating system (on build / deploy hosts):
Ubuntu
* Are you using an umbrella project (yes|no):
yes
### Verbose output

* Are there more information when running with `--verbose`?
```
EDELIVER TICKET_AGENT WITH UPGRADE COMMAND

-----> Upgrading to revision a18bb9a from branch master
-----> Detecting release versions on production hosts
Version RPC to 'ticket_agent@127.0.0.1' failed: {'EXIT', {undef, [{'Elixir.Edeliver',run_command, [[release_version,ticket_agent]], []}, {rpc,'-handle_call_call/6-fun-0-', 5, [{file,rpc.erl},{line,197}]}]}} is installed on host pushers@newpushers
-----> Deploying upgrades to 1 online hosts
-----> Checking whether installed version RPC to 'ticket_agent@127.0.0.1' failed: {'EXIT',
                                         {undef,
                                          [{'Elixir.Edeliver',run_command,
                                            [[release_version,ticket_agent]],
                                            []},
                                           {rpc,'-handle_call_call/6-fun-0-',
                                            5,
                                            [{file,rpc.erl},{line,197}]}]}} is in release store
Version RPC to 'ticket_agent@127.0.0.1' failed: {'EXIT', {undef, [{'Elixir.Edeliver',run_command, [[release_version,ticket_agent]], []}, {rpc,'-handle_call_call/6-fun-0-', 5, [{file,rpc.erl},{line,197}]}]}} not found in release store
-----> Building the upgrade from version RPC to 'ticket_agent@127.0.0.1' failed: {'EXIT',
                                         {undef,
                                          [{'Elixir.Edeliver',run_command,
                                            [[release_version,ticket_agent]],
                                            []},
                                           {rpc,'-handle_call_call/6-fun-0-',
                                            5,
                                            [{file,rpc.erl},{line,197}]}]}}
-----> Authorizing hosts
-----> Ensuring hosts are ready to accept git pushes
-----> Pushing new commits with git to: builder@localhost
Everything up-to-date
-----> Resetting remote hosts to a18bb9a57ac1c752691f434a83edfb22f72e3357
HEAD is now at a18bb9a adding edeliver to mix
-----> Cleaning generated files from last build
cleaning files in: .
Skipping repository deps/pdf_generator
Skipping repository deps/qrcode
-----> Checking out RPC
error: pathspec 'RPC' did not match any file(s) known to git.

A remote command failed on:

  builder@localhost

Output of the command is shown above and the command executed
on that host is printed below for debugging purposes:

FAILED with exit status 1:

    [ -f ~/.profile ] && source ~/.profile
    set -e
    cd /home/builder/app_build
    git checkout RPC
```

### Current behavior
mix edeliver upgrade production

Include executed edeliver command, error output etc.

### Expected behavior
I would be able to upgrade my build

**Comment by lessless** [comment]
Hi @veverkap ,

It looks like that your release store is missing a build on top of which it can build an update:

`Checking out RPC` <--- this is wrong, it should  be `Checking out <commit SHA>`

**Comment by veverkap** [comment]
@lessless how would I find out what is in my release store?

I'm building using Docker locally

```BUILD_HOST="localhost"
BUILD_USER="builder"
BUILD_AT="/home/builder/app_build"

PRODUCTION_HOSTS="newpushers" 
PRODUCTION_USER="pushers" 
DELIVER_TO="/home/pushers/app_release" ```

**Comment by lessless** [comment]
That should be local store, i.e.  in the `/home/builder/app_build` on your build host. Are you using mounted volume with Docker?

**Comment by lessless** [comment]
Also, that's why `Version RPC to 'ticket_agent@127.0.0.1' ` is failing - it's expecting that current version against which upgrade is being built is running in your build container, what I assume is not the case. 

Depending on the exact options that you are using with `upgrade` command it can also be a source of failure.  In general it seems like that's a configuration nuances for which I won't be really able to provide any more help. 
That's why I will close this issue for now. 

Feel free to ask around on elixirforum and #deployment channel on Slack  and reopen in case you are strongly positive that it's a bug or something in documentation can be improved!

**Comment by veverkap** [comment]
I am NOT using a mounted volume.  That probably is the problem.

**Comment by williamweckl** [comment]
I'm having the same issue, without any progress yet :(

Using umbrella too, Elixir 1.6.4, edeliver v1.5.0, distillery 1.5.2, ubuntu... Almost the same environment from @veverkap ...

**Comment by veverkap** [comment]
@williamweckl I ended up adding a mounted volume and that corrected it

**Comment by williamweckl** [comment]
I just tested and it happens only for umbrella... Even without mounted volume, non umbrella app works like a charm... :(

**Comment by williamweckl** [comment]
Just created an example repo: https://github.com/williamweckl/hotswap_umbrella.

```
[19:23] william@william-desktop:~/dev/hotswap_umbrella (master) $ mix edeliver version production

EDELIVER HOTSWAP_UMBRELLA WITH VERSION COMMAND

-----> getting release versions from production servers

production node:

  user    : podbot
  host    : hotswap
  path    : /home/podbot/app_release
  response: RPC to 'hotswap_umbrella@127.0.0.1' failed: {'EXIT',
                                             {{badmatch,nil},
                                              [{'Elixir.Edeliver',
                                                run_command,1,
                                                [{file,lib/edeliver.ex},
                                                 {line,63}]},
                                               {rpc,
                                                '-handle_call_call/6-fun-0-',
                                                5,
                                                [{file,rpc.erl},
                                                 {line,197}]}]}}

VERSION DONE!
```

**Comment by williamweckl** [comment]
After some days and a lot of red bulls I've got it to work! :D

I did a lot of things:

- removed `set include_system_libs: true` from environment prod
- configured all umbrella apps to use the same version, even seted version at umbrella's root `mix.exs`
- added :edeliver to `distillery config.exs` `set applications`
- added distillery and edeliver as dependency to all mix.exs files, even the umbrella's root
- added `:edeliver, :distillery` as `extra_applications` to all umbrella apps
- used command `mix edeliver build release` instead of `mix edeliver build release production`
- changed my release name (at `rel/config.exs`) to my main app instead of other name
- changed `APP=` (at .deliver/config) to my main app instead of other name

I think the last 2 configurations did the trick.

**Comment by lessless** [comment]
thanks @williamweckl !

**Comment by thelazycamel** [comment]
I had the same issues as above, whilst whilst following Digital Oceans how to deploy elixir/phoenix, after some head scratching i found simply upgrading the versions of edeliver/distillery fixed the issue 
current versions:
      {:edeliver, "~> 1.6.0"},
      {:distillery, "~> 2.0.10"}
also you will need to add :edeliver as the last item on the application list in mix.exs
