### ISSUE TITLE
Everything seems ok but server doesn't start

### ISSUE THREAD

**Issue by dokuzbir** [edeliver/edeliver#261]
### Precheck

I am testing a deploy example on my machine. I have a virtualbox ubuntuserver. I follow that guide
`https://www.digitalocean.com/community/tutorials/how-to-automate-elixir-phoenix-deployment-with-distillery-and-edeliver-on-ubuntu-16-04,`

How can i debug what is wrong ?

**Start production seems ok.** 

```
myproject$ mix edeliver start production

EDELIVER MYPROJECT WITH START COMMAND

-----> starting production servers

production node:

  user    : deneme
  host    : 192.168.1.90
  path    : /home/deneme/app_release
  response: 

START DONE!
```

**but server doesnt start**

```
deneme@ubuntu:~$ netstat -plnt
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      -               
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      2358/epmd       
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      -               
tcp6       0      0 :::80                   :::*                    LISTEN      -               
tcp6       0      0 :::4369                 :::*                    LISTEN      2358/epmd       
tcp6       0      0 :::22                   :::*                    LISTEN      -               
tcp6       0      0 ::1:5432                :::*                    LISTEN      - 
```

**Edeliver config**

```
APP="myproject"

BUILD_HOST="192.168.1.90"
BUILD_USER="deneme"
BUILD_AT="/home/deneme/app_build"

PRODUCTION_HOSTS="192.168.1.90" 
PRODUCTION_USER="deneme" 
DELIVER_TO="/home/deneme/app_release" 


pre_erlang_get_and_update_deps() {
  local _prod_secret_path="/home/deneme/app_config/prod.secret.exs"
  if [ "$TARGET_MIX_ENV" = "prod" ]; then
    __sync_remote "
      ln -sfn '$_prod_secret_path' '$BUILD_AT/config/prod.secret.exs'
    "
  fi
}

```

### Environment

* Edeliver version (`1.4.5`):
* Elixir version (`1.6.1.1`):
* Build tool and version (distillery 1.5.2):
* Operating system (on build ubuntu 14.04 / deploy hosts ubuntu 16.04):
* Are you using an umbrella project (no):

**Comment by lessless** [comment]
Hi @dokuzbir ,

Can you show the application logs please?

**Comment by dokuzbir** [comment]
Which logs should i look?
there is a error in app_release/myproject/var/sys.config 
**sys.config**

> %% Generated - edit/create /home/deneme/app_release/myproject/sys.config instead.
> [{sasl,[{errlog_type,error}]},
>  {logger,
>      [{console,
>           [{format,<<"$time $metadata[$level] $message\n">>},
>            {metadata,[request_id]}]},
>       {level,info}]},
>  {myproject,
>      [{'Elixir.MyprojectWeb.Endpoint',
>           [{render_errors,
>                [{view,'Elixir.MyprojectWeb.ErrorView'},
>                 {accepts,[<<"html">>,<<"json">>]}]},
>            {pubsub,
>                [{name,'Elixir.Myproject.PubSub'},
>                 {adapter,'Elixir.Phoenix.PubSub.PG2'}]},
>            {http,[{port,4000}]},
>            {load_from_system_env,true},
>            {url,[{host,<<"192.168.1.90">>},{port,80}]},
>            {cache_static_manifest,<<"priv/static/cache_manifest.json">>},
>            {server,true},
>            {code_reloader,false},
>            {secret_key_base,
>                <<"aIFw1VumPsjj969I4zBbT4lBo+0n56sw1dLfvAM48Z4ntM50pc/hx+/vD0YVCsMC">>}]}]}].
> 
>

**Comment by dokuzbir** [comment]
It resolved after i change my prod config.


old config 
```
config :myproject, MyprojectWeb.Endpoint,
  http: [port: 4000],
  url: [host: "192.168.1.90", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  code_reloader: false

```
new config

```
config :myproject, MyprojectWeb.Endpoint,
  http: [port: 4000],
  url: [host: "192.168.1.90", port: 80],
  cache_static_manifest: "priv/static/manifest.json",
  server: true,
  code_reloader: false
```

**Comment by lessless** [comment]
logs are located in project's `var/log` folder.

Thanks for update!
