### ISSUE TITLE
Using edeliver in a git monorepo 

### ISSUE THREAD

**Issue by Ciboulette** [edeliver/edeliver#262]
Hey, 

I would like to know if there is a config variable to indicate the Mix execution path.

I am working with a git mono repo organised like below:
core/
  +engine
  +worker
  +cli
  +website

I would like to indicate edeliver to build the release in the engine directory. 

when I launch `mix edeliver build release` it tries to build in the root directory.

Is-anyone have a suggestion ?

**Comment by lessless** [comment]
Hi @Ciboulette ,

please, use Issues to report bugs and provide suggestions. This question can be asked on Elixirforum, IRC or deployment channel on Slack.

Thanks.
