### ISSUE TITLE
Deploying releases from release store broken in edeliver 1.4.6

### ISSUE THREAD

**Issue by nulian** [edeliver/edeliver#264]
From version 1.4.6 edeliver gives this error when deploying form a release store.
Before 1.4.6 it works fine while releasing.

```
-----> Uploading archive of release 0.2.0+edge-devops1604buildhost-832-dc86d99 from remote release store
bash: line 3: cd: ~/releases/synapse: No such file or directory
Uploading release file failed
  source: ~/releases/synapse/synapse_0.2.0+edge-devops1604buildhost-832-dc86d99.release.tar.gz on deploy@build1.dev.betty.systems
  destination: /apps/synapse/project/synapse/synapse_0.2.0+edge-devops1604buildhost-832-dc86d99.tar.gz on deploy hosts
```

**Comment by lessless** [comment]
There was a bash scripts modifcations and there may be a problem with how home folder is picked up. Is `~/releases/synapse` a valid path?

**Comment by nulian** [comment]
On our source it is and is correctly handled in edeliver version 1.4.5. But in 1.4.6 i'm not sure where it's looking it will always give that error.

**Comment by lessless** [comment]
It looks like that this problem may share same cause with the #265 - something is wrong with release store path.
Sorry for the inconvenience.

**Comment by nulian** [comment]
Found out this is because of the posix compatibility I referenced.

**Comment by lessless** [comment]
closed via https://github.com/edeliver/edeliver/commit/96d64a8b19aa53b48d0fbd769aaa5c12eb0da2ef
