### ISSUE TITLE
Issue to start production after upgrade to erlang 21

### ISSUE THREAD

**Issue by romaluca** [edeliver/edeliver#273]
Hi, i upgrade my server to erlang 21. before of this, edeliver worked well.

Now if i try the command
`mix edeliver build release`

it returns:
`RELEASE BUILD OF S******P WAS SUCCESSFUL!`

and if i launch the command:

`mix edeliver deploy release to production`

it returns:

`DEPLOYED RELEASE TO PRODUCTION!`

and if i launch:

mix edeliver start production
it returns:

```
response: init terminating in do_boot ({cannot get bootfile,no_dot_erlang.boot})

Crash dump is being written to: erl_crash.dump...done
init terminating in do_boot ({cannot get bootfile,no_dot_erlang.boot})

Crash dump is being written to: erl_crash.dump...done
init terminating in do_boot ({cannot get bootfile,no_dot_erlang.boot})

Crash dump is being written to: erl_crash.dump...done


START DONE!
```

opening my homepage site something is loaded e something not 

launching
`mix edeliver stop production`
or
`mix edeliver migrate production`

i receive:
```
response: init terminating in do_boot ({cannot get bootfile,no_dot_erlang.boot})

Crash dump is being written to: erl_crash.dump...done
init terminating in do_boot ({cannot get bootfile,no_dot_erlang.boot})

Crash dump is being written to: erl_crash.dump...done
Node s*******p@127.0.0.1 is not running!

```

i tried to launch manually my application from server with:
`s*******p/bin$ ./s******p foreground`
and with this mode it works well...

how can i do for get the same result from edeliver?

Thanks

**Comment by lessless** [comment]
Hi @romaluca, what distillery version are you using?

**Comment by romaluca** [comment]
1.5.2
I've seen that also other people have the same issue:
[https://github.com/bitwalker/distillery/issues/426](https://github.com/bitwalker/distillery/issues/426)

**Comment by lessless** [comment]
Thanks for pointing this out. I left a comment there - seems that ball is on the distillery part of the field
