### ISSUE TITLE
Issue starting production nodes - not giving a failure reason

### ISSUE THREAD

**Issue by LukeWood** [edeliver/edeliver#286]
### Environment

* Edeliver version (`mix edeliver --version`):
edeliver v1.4.5 | https://github.com/boldpoker/edeliver
* Elixir version (`elixir -v`):
Elixir 1.6.4 (compiled with OTP 20)
* Build tool and version (distillery):
distillery 2.0.4
* Operating system (on build / deploy hosts):
macos/ubuntu
* Are you using an umbrella project (yes|no):
no, but I am working in a repo with multiple packages (one of which is a phoenix project)

### Verbose output

* Are there more information when running with `--verbose`?
nope
* Can you narrow down the code line causing the issue when running with `--debug`?
unfortunately no
* Please remove any private data from the output before pasting it here (login credentials, ip addresses user names etc.)

$mix edeliver start production --verbose

EDELIVER CLIENT WITH START COMMAND

-----> starting production servers

production node:

  user    : root
  host    : redacted
  path    : /home/root/redacted_releases
  response: mesg: ttyname failed: Inappropriate ioctl for device
▸  Received 'pang' from client@127.0.0.1!
▸  Possible reasons for this include:
▸    - The cookie is mismatched between us and the target node
▸    - We cannot establish a remote connection to the node
▸  Received 'pang' from client@127.0.0.1!
▸  Possible reasons for this include:
▸    - The cookie is mismatched between us and the target node
▸    - We cannot establish a remote connection to the node
▸  Remote call failed with: {:EXIT, :noproc}

START DONE!

### Current behavior
I run mix edeliver start production after deploying a release with mix edeliver deploy to production --version=X

it seems like edeliver thinks that the start was successful when it prints out the green "START DONE" message.

I have tried manually editing $HOME/.erlang.cookie on both my local and remote host

If I keep on running the command it will sometimes start and then the upgrade commands fail.

### Expected behavior

I would either expect edeliver to successfully start the application or give a failure message as to why the start failed.

**Comment by LukeWood** [comment]
will reopen when I get to add more detail

**Comment by LukeWood** [comment]
Here is the output after running mix edeliver start production - I have manually changed ~/.erlang.cookie on both servers to match

EDELIVER CLIENT WITH START COMMAND

-----> starting production servers

production node:

  user    : root
  host    : redacted
  path    : /root/redacted_releases
  response: mesg: ttyname failed: Inappropriate ioctl for device
▸  Received 'pang' from client@127.0.0.1!
▸  Possible reasons for this include:
▸    - The cookie is mismatched between us and the target node
▸    - We cannot establish a remote connection to the node
▸  Received 'pang' from client@127.0.0.1!
▸  Possible reasons for this include:
▸    - The cookie is mismatched between us and the target node
▸    - We cannot establish a remote connection to the node


START DONE!

**Comment by lessless** [comment]
@LukeWood set `DEBUG_BOOT=true` and try again. Let's see if there be anything interesting there.

**Comment by LukeWood** [comment]
just to clarify DEBUG_BOOT is an environment variable that get's replaced with replace os vars?

once I'm sure of this I'll give it another shot.

**Comment by lessless** [comment]
@LukeWood kind of. You see `./bin/*` scripts are not a part of Edeliver - they're generated by Distillery and `DEBUG_BOOT` is a Distillery debugging flag. So, yes - it's an environment variable, but it has nothing to do with replace os vars feature.

**Comment by LukeWood** [comment]
So an update here:

DEBUG_BOOT=true did not give me any more information, but my servers have started consistently starting up again for some reason unknown to me.

I'm going to go ahead and close this as it's entirely possible I was doing something silly that was causing the boot to fail due to inexperience but if I am ever able to recreate the issue I will comment here again.

Thanks for your help and patience!

**Comment by lessless** [comment]
No problems, thanks for reporting!
