### ISSUE TITLE
Unable to run 'mix edeliver build release production' without exporting vars first

### ISSUE THREAD

**Issue by skota** [edeliver/edeliver#287]
### Environment

* Edeliver version (`mix edeliver --version`): edeliver v1.4.5 | https://github.com/boldpoker/edeliver
* Elixir version (`elixir -v`): Elixir 1.6.4 (compiled with OTP 20)
* Build tool and version (distillery):  :distillery, "~> 2.0"
* Operating system (on build / deploy hosts): ubuntu/ubuntu
* Operating system (dev): macos
* Are you using an umbrella project (yes|no):

### The problem
edeliver is not able to find BUILD_HOST,BUILD_USER, BUILD_AT when i run this command - " mix edeliver build release production --verbose"

### Verbose output
* Can you narrow down the code line causing the issue when running with `--debug`? 
[debug-output.txt](https://github.com/edeliver/edeliver/files/2345880/debug-output.txt)

### Current behavior
I have to export the vars from command line before i can run "mix edeliver build release production --verbose"

### Expected behavior
I should be able to start the command without exporting vars

**Comment by lessless** [comment]
Please refer to the documentation https://github.com/edeliver/edeliver#quick-start (variables can be defined in `.deliver/config`)
