### ISSUE TITLE
No ability to execute code before upgrade release

### ISSUE THREAD

**Issue by romikoops** [edeliver/edeliver#289]
Edeliver is amazing tool and it allows to handle both ordinary releasing and hot deployments.
However I faced with missing Hook "pre_upgrade_release()" similar to "post_upgrade_release()".
My motivation is copying fresh version of config file before upgrade. Currently it is possible to use "post_upgrade_release()" hook only but it requires to restart app and as result kills idea of hot deployment with zero downtime. 

Here is more details...

For ordinary release I use following hook and it works perfectly

```
post_extract_release_archive() {
    status "Copying sys.config file to production host"
    scp $BUILD_USER@$BUILD_HOST:$BUILD_AT/_build/prod/rel/$APP/releases/$VERSION/sys.config $PRODUCTION_USER@$PRODUCTION_HOSTS:/srv/ccsix/configs/$APP
}
```

Unfortunately this hook is not executed for *upgrade* command. `post_upgrade_release()` hook is useful, but it requires app restart to apply config changes. I reviewed the code and info on wiki and dit not found `pre_upgrade_release()` hook. I wonder why it is missing and what technical challenge is to implement it. Thanks in advance!

**Comment by lessless** [comment]
Thanks for the kind words @romikoops ,

Did you look at https://github.com/edeliver/edeliver/blob/master/libexec/erlang#L752  ? `pre_upgrade_release` is mentioned there but yeah, it's not in the wiki. Just give it a chance and let's see if it works for you.

**Comment by romikoops** [comment]
Yes, it works! I have actualized wiki page with all missing hooks
https://github.com/edeliver/edeliver/wiki/Run-additional-build-tasks
