### ISSUE TITLE
Impossible to use new asset files after hot-code upgrade of phoenix app with auto version

### ISSUE THREAD

**Issue by romikoops** [edeliver/edeliver#290]
I have ordinary phoenix app (v 1.3.3) with enabled edeliver auto versioning. In case of changed ccs or javascript assets my phoenix app does not load new assets after hot deploy. After quick investigation I found issue https://github.com/edeliver/edeliver/issues/175 with a solution without auto-versioning. I wonder how to solve it if I use simple auto-versioning strategy AUTO_VERSION="git-revision". I need some idea how to solve the issue, cause now I can not use hot deployment with zero downtime in production. It requires `mix edeliver restart production` command execution to fix it. I have started to think about getting rid of an auto-version strategy entirely and adjust versions in classical way via bumping version in mix.exs, commiting it and use `version: Mix.Project.config[:version]` in my config/prod.exs. Please share any workarounds or ideas how to solve the issue and keep amazing auto-versioning feature in Edeliver!

**Comment by lessless** [comment]
Hi @romikoops,

Did you try last suggestion in the linked issue? Assets are being reloaded just fine in our app.

**Comment by lessless** [comment]
What I mean is that Edeliver is changing release version for you through `mix release.version` and then you have to pick it up through `version` option as folks suggested.
There is a slight chances that you are running into Distillery 2.x compatibility issue but odds of that are tiny.
