### ISSUE TITLE
Status 255: build fails

### ISSUE THREAD

**Issue by kristofvanwoensel** [edeliver/edeliver#297]
Hi
I'm trying to release a phoenix application with edeliver following the steps explained here. I have browsed the internet and found some people having the same problem, but no matter what I do, I keep on getting the same error below.

I can login without password with SSH
my user (deploy) has all rights
User can use git with ssh

**Errormessage:**

-----> Authorizing hosts
-----> Ensuring hosts are ready to accept git pushes
A remote command failed on:

deploy@206.189.109.156

Output of the command is shown above and the command executed
on that host is printed below for debugging purposes:

FAILED with exit status 255:

current_shell="$0" || :
[ -z "$current_shell" ] && current_shell="$SHELL"
case "$current_shell" in
  (*bash*) echo 'bash is installed and the default shell'  ;;
  (*zsh*)  echo  'zsh is installed and the default shell'  ;;
  (*)
   echo
   echo "You are using an unsupported shell: '$current_shell'"
   echo "edeliver requires either bash or zsh to be installed"
   echo "and the default shell for the build user 'deploy'"
   echo "on your build host: '206.189.109.156'."
   exit 1
   ;;
esac
set -e
if [ ! -d ~/myapps/builds ]
then
  mkdir -p ~/myapps/builds
  cd ~/myapps/builds
  git init
  git config receive.denyCurrentBranch ignore
else
  cd ~/myapps/builds
  git config receive.denyCurrentBranch ignore
fi

**This is my .deliver/config file:**

APP="boomgaard"
BUILD_HOST="206.189.109.156"
BUILD_USER="deploy"
BUILD_AT="~/myapps/builds"

RELEASE_DIR="~/myapps/builds/"

GIT_CLEAN_PATHS="_build rel priv/static"

PRODUCTION_HOSTS="fruitvarieteiten.com"
PRODUCTION_USER="deploy"
DELIVER_TO="/home/deploy"

pre_erlang_get_and_update_deps() {
local _prod_secret_path="/home/deploy/prod.secret.exs"
if [ "$TARGET_MIX_ENV" = "prod" ]; then
__sync_remote "
  ln -sfn '$_prod_secret_path' '$BUILD_AT/config/prod.secret.exs'
"
fi
}

pre_erlang_clean_compile() {
 status "Running phoenix.digest" # log output prepended with "----->"
 __sync_remote " # runs the commands on the build host

source ~/.profile

set -e # fail if any command fails (recommended)
cd '$BUILD_AT' # enter the build directory on the build host (required)

**Comment by kristofvanwoensel** [comment]
Solved it myself by adding my public key to .ssh/authorized_keys

**Comment by lessless** [comment]
Good to know!

**Comment by JamesSchiiller** [comment]
make sure your "build_app" in .deliver/config is created on remote build server
and cd into build_app on remote build server and do the following commands, I didn't need to clone the repo first.
In the edeliver error message in the if else statements you can do those manually
I went to the build host and manually ran the git commands it lists in the error and it worked.
$ git init &> /dev/null
$ git config receive.denyCurrentBranch ignore
https://github.com/edeliver/edeliver/issues/134
