### ISSUE TITLE
New configuration options on prod.secret.exs not updating 

### ISSUE THREAD

**Issue by tedi** [edeliver/edeliver#323]
I originally had an issue connecting to a PostgreSQL DB. After a bit of debugging, I saw that the issue was with the Database service I'm using requiring SSL (DigitalOcean).  I added ssl: true to the config and updated all environments accordingly. However when I start the production environment, it seems to be using the old configuration options. 

I tried a new release, cleaned my server folders and re-deployed everything, the same configuration options seem to be used. I've been hitting my head on this issue for quite a while. Any direction would be much appreciated.

Just to clarify that it wasn't only a SSL flag issue, I tried pointing the config to a totally different database, but it still uses the old configuration.

I've also confirmed that it's not an issue with the database, as I can connect with other clients.

Although I believe irrelevant, here's the original database error message:
`[11-1] user=***,db=***,app=[unknown],client=*** FATAL: no pg_hba.conf entry for host "****", user "****", database "****", SSL off`

**Comment by speeddragon** [comment]
Check if this is the same issue as https://github.com/edeliver/edeliver/issues/314

**Comment by tedi** [comment]
> Check if this is the same issue as #314

Thanks for the reference! Manually updating the version actually did fix it, and weird enough, subsequent pushes automatically updated the file (no, I didn't have to do anything with the hooks as suggested in the referenced post). 

Thanks again!
