### ISSUE TITLE
Not compatible with elixir 1.11.3 yet

### ISSUE THREAD

**Issue by n-studio** [edeliver/edeliver#339]
### Environment

* Edeliver version (`mix edeliver --version`): 1.8.0 (master)
* Elixir version (`elixir -v`): 1.11.3
* Build tool and version (distillery): distillery
* Operating system (on build / deploy hosts): deploy
* Are you using an umbrella project (yes|no): no

### Current behavior

I tried to deploy an empty Phoenix app (1.5.7) with elixir 1.11.3, no error message whatsoever but the app wouldn't start via `bin/my_app start`. I downgraded elixir to 1.10.4 and it worked flawlessly.

### Expected behavior

My guess is that edeliver is just not compatible with elixir 1.11.3 yet, I'm opening an issue just so people don't lose their time like I did and know they have to downgrade elixir to 1.10.x if they want to use edeliver.

**Comment by gamache** [comment]
I am using Edeliver 1.8.0 with Elixir 1.11.3 without any apparent problems.

**Comment by kenny-evitt** [comment]
I'm using `edeliver` with Elixir `1.12.3` without issue.

The newer versions of Elixir (and/or Erlang/OTP) might require newer versions of *system* packages – I've run into that during several upgrades of Elixir/Erlang/OTP for the relevant project.

Check your app's logs, or try running your app using the 'start with console' command. Either should provide *some* info about why it won't start for newer versions of Elixir.

**Comment by n-studio** [comment]
I don't have time to check now but it's most probably an issue in my app config. Thank you for your comments. Closing now.
