### ISSUE TITLE
No releases shown when running `mix edeliver show releases`

### ISSUE THREAD

**Issue by NexPB** [edeliver/edeliver#358]
### Environment

* Edeliver version (`mix edeliver --version`): edeliver v1.9.0
* Elixir version (`elixir -v`): Elixir 1.13.4 (compiled with Erlang/OTP 23)
* Build tool and version (distillery): mix
* Operating system (on build / deploy hosts): Docker on MacOS
* Are you using an umbrella project (yes|no): No

### Current behavior

Runnning `mix edeliver show releases` does not show any releases available on the registry at index.docker.io

Example output from hitting the endpoint `https://index.docker.io/v2/lunarisjp/example/tags/list`: `++ _out='{"name":"lunarisjp/example","tags":["0.1.091d08c2-lorenzoedeliver-91d08c2","0.1.091d08c2-lorenzoedeliver-latest","0.1.091d08c2-lorenzoedeliver-master"]}'`

### Expected behavior

Show all available releases.

I assume it has to do with the regex on https://github.com/edeliver/edeliver/blob/master/libexec/erlang#L871

**Comment by bharendt** [comment]
@NexPB Did you set the `DOCKER_REGISTRY_TOKEN` in your `.deliver/config`? Authentication is required to access all tags at the registry. The used token needs `pull` rights.

**Comment by NexPB** [comment]
Yes, the `DOCKER_REGISTRY_TOKEN ` was set and I verified it was working using a regular curl request(s) calling the API endpoint.

The output provided here, was directly taken from running `mix edeliver show releases --debug`;
```
_out='{"name":"lunarisjp/example","tags":["0.1.091d08c2-lorenzoedeliver-91d08c2","0.1.091d08c2-lorenzoedeliver-latest","0.1.091d08c2-lorenzoedeliver-master"]}'
```

Which seems to be correct according to the docs found at https://docs.docker.com/registry/spec/api/#get-tags, it seems that the shell script is not parsing this output correctly.

**Comment by bharendt** [comment]
I could reproduce the issue with the DockerHub registry by using 
```
REGISTRY_USER="username"
REGISTRY_IMAGE="dockerimage"
ACCESS_TOKEN="generated on docker hub"
DOCKER_REGISTRY_TOKEN="$(curl --silent -u "$REGISTRY_USER:$ACCESS_TOKEN" \
                              --get --data-urlencode "service=registry.docker.io" \
                              --data-urlencode "scope=repository:${REGISTRY_USER}/${REGISTRY_IMAGE}:pull" \
                              "https://auth.docker.io/token" | jq --raw-output '.token')";        
```
as Bearer token for the registry list-tags request `https://${_registry}/v2/${_name}/${_image}/tags/list`. Will add this to the documentation and try to simplify this. @NexPB did you create the `DOCKER_REGISTRY_TOKEN` on a similar way?

However: it turned out, that the DockerHub registry provides much less information about the tags, e.g. no timestamps. So tags cannot be sorted and are displayed then in a random order.

DockerHub response on `https://${_registry}/v2/${_name}/${_image}/tags/list`:

```
{"name":"_name/_image","tags":["tag1","tag2"]}
```

while the Google Container Registry provides more detailed information like the creation date which is used to sort the tags before displaying it:

```
{"manifest": {"sha256:03302a…": {"timeCreatedMs":…, "tag":["tag1"], …}, "tags":["tag1","tag2"]}
```

Added a fallback to simple tag listing without creation time sorting in #359.

**Comment by NexPB** [comment]
Yeah pretty much the same way as you:

```sh
DOCKER_API_JSON=$(curl -s -H -X GET 'https://auth.docker.io/token?service=registry.docker.io&scope=repository:team/example-repo:pull,push' \
--header 'Authorization: Basic SUPER_SECRET')
DOCKER_REGISTRY_TOKEN=$(echo $DOCKER_API_JSON | sed "s/{.*\"token\":\"\([^\"]*\).*}/\1/g")
```

Thanks for fixing! 😄

**Comment by bharendt** [comment]
It is now possible to set `DOCKER_HUB_ACCESS_TOKEN` in the config to generate the token automatically. 
Fetching a token and set it as generic `DOCKER_REGISTRY_TOKEN="$(…)"` is not necessary then any more if Docker Hub is used as registry. @NexPB Thanks, I used your `sed` command to extract the token without requiring [jq](https://stedolan.github.io/jq/).
