### ISSUE TITLE
Custom environment names

### ISSUE THREAD

**Issue by gaynetdinov** [edeliver/edeliver#66]
Is it possible to have different environment names besides `staging` and `production`?

**Comment by bharendt** [comment]
Yes, it is possible. It is not (yet) directly supported by edeliver, but you can use additional deploy environments by customizing your `.deliver/config`.

If you add a variable with the uppercase name of your additional env with a tailing `_NODES` containing the nodes for the additional environment (separated by a space) in the format `user1@host1:path1 user2@host2:path2` as value, you will be able to use the node commands like `edeliver version beta` or `edeliver start qa` with the additional environments (`beta` and `qa` in this example):
```sh
# ./deliver/config
BETA_NODES="${BETA_USER}@${BETA_HOST}:${DELIVER_TO}"
QA_NODES="${QA_USER}@${QA_HOST}:${DELIVER_TO}"

```

To be able to deploy to additional environments you have to override the `STAGING_HOSTS` and `STAGING_USER` config:

```sh
# ./deliver/config
if [[ "$DEPLOY_ENVIRONMENT" = "beta" ]]; then
  STAGING_HOSTS="$BETA_HOSTS"
  STAGING_USER="$BETA_USER"
elif [[ "$DEPLOY_ENVIRONMENT" = "qa" ]]; then
  STAGING_HOSTS="$QA_HOSTS"
  STAGING_USER="$QA_USER"
fi
```

You then still would get the following warning if you eg. deploy to beta 

```sh
$ edeliver deploy release to beta
Unknown argument beta ignored

DEPLOYING RELEASE OF BOLDPOKER_GAME APP TO BETA HOSTS

....
```

To avoid that warning you can add a `.deliver/help` file and accept the custom environments as a valid argument in the `accepts_custom_command_argument` function:

```sh
#!/usr/bin/env bash
#./deliver/help
print_custom_commands_help() {
  echo -e "  ${txtbld}Custom Deploy Environments:${txtrst}
  edeliver deploy release|upgrade [to] staging|beta|qa|production
  "
}

accepts_custom_command_argument() {
  local _command="$1"
  local _argument="$2"
  case "${_command}" in
    (deploy)
      case "${_argument}" in
        (staging|beta|qa|production)
          DEPLOY_ENVIRONMENT="${_argument}"
          return 0 ;;
        ("") return 0 ;; # default: 'staging'
        (*)  return 1 ;; # unknown deploy environment
      esac ;;
    (*) return 1 ;; # unknown custom command
  esac
}
```

This is usually used to extend edeliver by adding custom commands, e.g. you could add something like `edeliver activate backup nodes` etc. and then specify there, that `activate`, `backup` and `nodes` are valid arguments. 

So I hope this workaround helps to add custom deploy environments, but I think we could / should add something like this for the next release to have an more easy and clear way to use additional deploy environments:

```sh
# .deliver/config
DEPLOY_ENVIRONMENTS="production staging beta qa xy" # default: 'production beta'

PRODUCTION_HOSTS="..."
PRODUCTION_USER="..."

STAGING_HOSTS="..."
STAGING_USER="..."

BETA_HOSTS="..."
BETA_USER="..."

QA_HOSTS="..."
QA_USER="..."

XY_HOSTS="..."
XY_USER="..."

```

**Comment by gaynetdinov** [comment]
Thank you for such a great explanation! ❤️ 
Do you think it would make sense to transform this comment into a wiki page?

**Comment by johannesE** [comment]
I copied that into a new wiki page here https://github.com/edeliver/edeliver/wiki/Custom-environments-besides-staging-and-production.
